#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for tcop
#
#-------------------------------------------------------------------------

subdir = src/backend/tcop
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

OBJS= dest.o fastpath.o postgres.o pquery.o utility.o

include $(top_srcdir)/src/backend/common.mk
