#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for utils/time
#
#-------------------------------------------------------------------------

subdir = src/backend/utils/time
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = combocid.o snapmgr.o

include $(top_srcdir)/src/backend/common.mk
