#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for main
#
#-------------------------------------------------------------------------

subdir = src/backend/main
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

OBJS = main.o

include $(top_srcdir)/src/backend/common.mk
