#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for storage/sync
#
#-------------------------------------------------------------------------

subdir = src/backend/storage/sync
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = sync.o

include $(top_srcdir)/src/backend/common.mk
