#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for access/tablesample
#
#-------------------------------------------------------------------------

subdir = src/backend/access/tablesample
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = bernoulli.o system.o tablesample.o

include $(top_srcdir)/src/backend/common.mk
