#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for statistics
#
#-------------------------------------------------------------------------

subdir = src/backend/statistics
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

OBJS = extended_stats.o dependencies.o mcv.o mvdistinct.o

include $(top_srcdir)/src/backend/common.mk
