#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for access/table
#
#-------------------------------------------------------------------------

subdir = src/backend/access/table
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = table.o tableam.o tableamapi.o

include $(top_srcdir)/src/backend/common.mk
