#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for storage/large_object
#
#-------------------------------------------------------------------------

subdir = src/backend/storage/large_object
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = inv_api.o

include $(top_srcdir)/src/backend/common.mk
