#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for utils/init
#
#-------------------------------------------------------------------------

subdir = src/backend/utils/init
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = globals.o miscinit.o postinit.o

include $(top_srcdir)/src/backend/common.mk
