#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for backend/partitioning
#
#-------------------------------------------------------------------------

subdir = src/backend/partitioning
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

OBJS = partbounds.o partdesc.o partprune.o

include $(top_srcdir)/src/backend/common.mk
