/*-----------------------------------------------------------------------
 *
 * UCharIterator support for multibyte encodings, suitable for
 * ucol_strcollIter() and ucol_nextSortKeyPart().
 *
 * ICU itself only provides uiter_setUTF8() and trivial UTF-16 iterators, but
 * icu4c/source/common/uiter.cpp contemplates built-in conversion support
 * along these lines in comments.  Progress appears to have stalled, but
 * user-supplied implementations are supported.
 *
 * This implementation converts PG_UITER_MB_MIN_CONVERT_SIZE initially, and
 * then ever larger chunks as required to offset overheads as the likelihood
 * of equal strings increases.  If necessary it converts the whole string into
 * palloc'd memory, though strings up to PG_UITER_MB_SMALL_BUFFER_SIZE require
 * no allocation.
 *
 * In our use case, strings usually differ close to the beginning unless they
 * are equal, and varlena.c already has a memcpy() check for binary equality
 * before collating.  This simplification is a reasonable trade-off and
 * allocation is expected to be rare.
 *
 * Differences compared to uiter_setUTF8():
 *
 * - incrementally finds the NUL terminator if length is set to -1, instead of
 *   calling strlen() on the whole input string
 *
 * - keeps whole char16_t string so far, allocating if necessary, providing
 *   O(1) backward jumps, while uiter_setUTF8() grovels character by character
 *   between indexes or from the start; it's unclear how much that matters
 *   with the jumps actually generated by the collation algorithm (many
 *   locales probably only use .next, .previous and .move to zero?)
 *
 * - this approach also anticipates potential incremental detoasting with a
 *   callback to fetch source data (not yet attempted), where the cost of
 *   jumping backwards without caching the converted string would surely be
 *   much higher
 *
 * - needs a pg_uiter_close() function to free context->buf if
 *   context->buf_small turns out to be too small (uiter.cpp's comments also
 *   mention a potential future uiter_close() for this reason)
 *
 * - initialization can be split into two steps,
 *   pg_uiter_initMultibyteContext() and then pg_uiter_setMultibyteString()
 *   for each new string; that division avoids storing ~240 bytes for every
 *   collation operation, if client code can arrange to reuse UCharInterator
 *   and PgUCharIteratorMultibyteContext objects initialized once; a simple
 *   function pg_uiter_setDbEncodingString() is also provided as a drop-in
 *   equivalent of uiter_setUTF8() for database encoding
 *
 * Portions Copyright (c) 2002-2026, PostgreSQL Global Development Group
 *
 * src/backend/utils/adt/pg_locale_icu_iter.c
 *
 *-----------------------------------------------------------------------
 */

#include "postgres.h"

#ifdef USE_ICU
#include "utils/pg_locale_icu.h"

#include <unicode/uiter.h>

static inline bool
pg_uiter_mb_can_convert_more(UCharIterator *iter)
{
	PgUCharIteratorMultibyteContext *context = pg_uiter_mb_context(iter);

	if (context->src_nul_terminated)
		return context->src[iter->start] != 0;
	else
		return iter->start < iter->length;
}
						 
static void
pg_uiter_mb_convert_more(UCharIterator *iter, int32_t new_limit)
{
	PgUCharIteratorMultibyteContext *context = pg_uiter_mb_context(iter);
	char16_t *buf_begin;
	char16_t *buf_end;
	const char *src_begin;
	const char *src_end;
	UErrorCode status;

	Assert(new_limit > iter->limit);

	/*
	 * Round up to convert size, and double that for next time to amortize all
	 * these cycles.
	 */
	if (new_limit < iter->limit + context->buf_convert_size)
		new_limit = iter->limit + context->buf_convert_size;
	if (context->buf_convert_size < PG_UITER_MB_MAX_CONVERT_SIZE)
		context->buf_convert_size *= 2;
	
	/* Out of space? */
	if (unlikely(new_limit > context->buf_capacity))
	{
		size_t new_capacity = context->buf_capacity * 2;

		if (new_limit > new_capacity)
			new_capacity *= 2;

		if (context->buf == context->buf_small)
		{
			context->buf = palloc_array(char16_t, new_capacity);
			memcpy(context->buf,
				   context->buf_small,
				   sizeof(char16_t) * iter->limit);
		}
		else
		{
			context->buf = repalloc_array(context->buf,
										  char16_t,
										  new_capacity);
		}
		context->buf_capacity = new_capacity;
	}

	/*
	 * For NUL-terminated strings, advance iter->length.  The search for NUL
	 * is capped at the maximum number of extra bytes we could possibly need
	 * to convert up to new_limit.
	 *
	 * XXX We could be more accurate instead of assuming the worst, but the
	 * cost of doing so probably exceeds the cost of overshooting.
	 */
	if (context->src_nul_terminated)
	{
		int32_t char16_out;
		int32_t max_bytes_in;
		int32_t have_bytes_in;

		char16_out = new_limit - iter->limit;
		max_bytes_in = char16_out * ucnv_getMaxCharSize(context->converter);
		Assert(iter->length >= iter->start);
		have_bytes_in = iter->length - iter->start;
		if (have_bytes_in < max_bytes_in)
			iter->length += strnlen(context->src + iter->length,
									max_bytes_in - have_bytes_in);
	}
	
	src_begin = context->src + iter->start;
	src_end = context->src + iter->length;
	Assert(src_begin < src_end);

	buf_begin = context->buf + iter->limit;
	buf_end = context->buf + new_limit;
	Assert(buf_begin < buf_end);

	status = U_ZERO_ERROR;
	ucnv_toUnicode(context->converter,
				   &buf_begin, buf_end,
				   &src_begin, src_end,
				   NULL,
				   context->src_nul_terminated ? *src_end == 0 : true,
				   &status);
	if (U_FAILURE(status) && status != U_BUFFER_OVERFLOW_ERROR)
		ereport(ERROR,
				(errmsg("%s failed: %s", "ucnv_toUnicode",
						u_errorName(status))));

	iter->limit = buf_begin - context->buf;
	iter->start = src_begin - context->src;
}

static UChar32
pg_uiter_mb_current(UCharIterator *iter)
{
    PgUCharIteratorMultibyteContext *context = pg_uiter_mb_context(iter);

	if (iter->index < iter->length)
		return context->buf[iter->index];

	return U_SENTINEL;
}

static UChar32
pg_uiter_mb_next(UCharIterator *iter)
{
    PgUCharIteratorMultibyteContext *context = pg_uiter_mb_context(iter);

	if (iter->index < iter->limit)
		return context->buf[iter->index++];

	if (!pg_uiter_mb_can_convert_more(iter))
		return U_SENTINEL;

	pg_uiter_mb_convert_more(iter, iter->index + 1);
	
	Assert(iter->index < iter->limit);

	return context->buf[iter->index++];
}

static UChar32
pg_uiter_mb_previous(UCharIterator *iter)
{
    PgUCharIteratorMultibyteContext *context = pg_uiter_mb_context(iter);

	if (iter->index > 0)
		return context->buf[--iter->index];

	return U_SENTINEL;	
}

static int32_t
pg_uiter_mb_getIndex(UCharIterator *iter, UCharIteratorOrigin origin)
{
    switch(origin) {
    case UITER_ZERO:
    case UITER_START:
        return 0;
    case UITER_CURRENT:
		return iter->index;
    case UITER_LIMIT:
		return iter->limit;
    case UITER_LENGTH:
		return iter->length;
    default:
        return -1;
    }
}

static int32_t
pg_uiter_mb_move(UCharIterator *iter,
				 int32_t delta,
				 UCharIteratorOrigin origin)
{
	int32_t abs_index = pg_uiter_mb_getIndex(iter, origin) + delta;

	/* Clamp to beginning of buffer. */
	if (abs_index < 0)
		abs_index = 0;

	/* Try to convert more before clamping at limit. */
	if (unlikely(abs_index >= iter->limit))
	{
		if (pg_uiter_mb_can_convert_more(iter))
			pg_uiter_mb_convert_more(iter, abs_index + 1);

		if (abs_index > iter->limit)
			abs_index = iter->limit;
	}

	iter->index = abs_index;
	return iter->index;
}

static pg_always_inline UBool
pg_uiter_mb_hasNext(UCharIterator *iter)
{
	return iter->index < iter->limit || pg_uiter_mb_can_convert_more(iter);
}

static UBool
pg_uiter_mb_hasPrevious(UCharIterator *iter)
{
	return iter->index > 0;
}

static uint32_t
pg_uiter_mb_getState(const UCharIterator *iter)
{
	return iter->index;
}

static void
pg_uiter_mb_setState(UCharIterator *iter, uint32_t state, UErrorCode *status)
{
	if (U_FAILURE(*status))
		return;
	
	if (state > iter->limit)
		*status = U_INDEX_OUTOFBOUNDS_ERROR;
	else
		iter->index = state;
}

/*
 * Set up the parts of iter and context that remain fixed when reused by
 * multiple cycles of pg_uiter_openMultibyteString(), pg_uiter_close().
 */
void
pg_uiter_initMultibyteContext(UCharIterator *iter,
							  PgUCharIteratorMultibyteContext *context,
							  UConverter *converter)
{
	static const UCharIterator pg_uiter_mb_prototype = {
		.getIndex = pg_uiter_mb_getIndex,
		.move = pg_uiter_mb_move,
		.hasNext = pg_uiter_mb_hasNext,
		.hasPrevious = pg_uiter_mb_hasPrevious,
		.current = pg_uiter_mb_current,
		.next = pg_uiter_mb_next,
		.previous = pg_uiter_mb_previous,
		.getState = pg_uiter_mb_getState,
		.setState = pg_uiter_mb_setState,
	};

	*iter = pg_uiter_mb_prototype;
	iter->context = context;
	context->converter = converter;
}

#endif
