#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for access/index
#
#-------------------------------------------------------------------------

subdir = src/backend/access/index
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = amapi.o amvalidate.o genam.o indexam.o

include $(top_srcdir)/src/backend/common.mk
